### PR TITLE
import features from fork

### PR DESCRIPTION
**Pull request by sawanoboly**
Test

### CODE REVIEW

**Comment by sawanoboly** [comment]
Hi, @dmagliola  Would you mind if I'll merge your code ?

(I don't know whether is sent notification by write a message here..)

**Comment by dmagliola** [comment]
Hi!
Yeah, absolutely! I was going to make a pull request later and ask you to merge them in, so by all means I'd be delighted if you do! Thank you!

I'm probably going to make a couple more changes to it today, I'll let you know if I do.
Thanks!

**Comment by sawanoboly** [comment]
Oh, I was mistaken to have already completed. I've decided to wait for your update, thanks :smile:

**Comment by dmagliola** [comment]
Alright, all done, merge away!
Thanks again!

**Comment by sawanoboly** [comment]
Great work!

**Comment by dmagliola** [comment]
Excellent, thanks!

**Comment by dmagliola** [comment]
Any chance you can do a Rubygems release so I can point ot the gem without specifiying the github URL?

**Comment by sawanoboly** [comment]
@dmagliola 

I've released 0.3.0 with new features. https://rubygems.org/gems/mandrill-template-manager/versions/0.3.0

**Comment by sawanoboly** [comment]
Ah, we can build and install locally, such as below.

```
$ gem build mandrill-template-manager.gemspec
$ gem install -l mandrill-template-manager.0.x.x.gem
```

or, add to Gemfile and bundle it.

```
gem 'mandrill-template-manager', path: './path/to/working_directory'
```

**Comment by dmagliola** [comment]
Awesome, thanks!

**Pull request merged**
